import { readFileSync } from "node:fs";
import * as cheerio from "cheerio";
const $ = cheerio.load(readFileSync("./B0D817HX57.html", "utf8"));
console.log("How many nodes match the LAST fallback selector?");
const sel = 'span[class*="a-price"] span[class*="a-price-whole"]';
const whole = $(sel);
console.log("  a-price-whole matches:", whole.length);
whole.slice(0, 6).each((i, el) => console.log(`    [${i}] "${$(el).text().trim()}"`));
const frac = $('span[class*="a-price"] span[class*="a-price-fraction"]');
console.log("  a-price-fraction matches:", frac.length);
frac.slice(0, 6).each((i, el) => console.log(`    [${i}] "${$(el).text().trim()}"`));
console.log("\nThe bug: .text() on a MULTI-node selection CONCATENATES.");
console.log('  $(sel).text()          =', JSON.stringify($(sel).text().trim().slice(0,40)));
console.log('  $(sel).first().text()  =', JSON.stringify($(sel).first().text().trim()));
console.log('  frac.text()            =', JSON.stringify(frac.text().trim().slice(0,40)));
console.log('  frac.first().text()    =', JSON.stringify(frac.first().text().trim()));
console.log("\nWhy python says null: is the price block even present?");
console.log("  #corePrice_feature_div :", $("#corePrice_feature_div").length);
console.log("  priceToPay             :", $('span[class*="priceToPay"]').length);
console.log("  availability text      :", JSON.stringify($("#availability").text().trim().slice(0,60)));
