"""users table with per-area permissions

Named logins replace "which of the two passwords did you type". Permissions are a
comma-separated list of area keys — see app/permissions.py for why areas rather than
routes, and why the list is a column rather than a join table.

**A new table, so this migration cannot lose data**, which is the one thing worth
checking before it runs on the EC2 box holding real scraped history. It adds nothing to
an existing table and rewrites no rows. That is also why the autogenerated form is kept
almost verbatim: the `brand_rank` migration needed hand-editing because a NOT NULL
column on a populated table fails, and none of that applies here.

It seeds NO users on purpose. Seeding an admin would mean either a hardcoded password
in schema history (which is then in git forever) or a generated one nobody sees. The
existing APP_PASSWORD login keeps working instead, and the owner creates real accounts
from the Users panel once he is in — so there is no window where nobody can sign in.

Revision ID: 394fc6f28429
Revises: 0f85fa400957
Create Date: 2026-08-10 19:01:55.366783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '394fc6f28429'
down_revision: Union[str, None] = '0f85fa400957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('permissions', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
