"""initial schema

Revision ID: da6e9b47821c
Revises: 
Create Date: 2026-07-30 15:39:29.627059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6e9b47821c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('churn_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=True),
    sa.Column('period_label', sa.String(length=50), nullable=True),
    sa.Column('total_asins', sa.Integer(), nullable=True),
    sa.Column('keep_count', sa.Integer(), nullable=True),
    sa.Column('monitor_count', sa.Integer(), nullable=True),
    sa.Column('churn_count', sa.Integer(), nullable=True),
    sa.Column('no_data_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=30), nullable=False),
    sa.Column('invoice_number', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.String(length=50), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('supplier_gstin', sa.String(length=20), nullable=True),
    sa.Column('recipient_gstin', sa.String(length=20), nullable=True),
    sa.Column('recipient_state', sa.String(length=50), nullable=True),
    sa.Column('fc_code', sa.String(length=10), nullable=True),
    sa.Column('transporter', sa.String(length=100), nullable=True),
    sa.Column('total_qty', sa.Integer(), nullable=True),
    sa.Column('total_taxable', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_igst', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('invoice_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('marketplace', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asin', sa.String(length=10), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('use_by', sa.String(length=50), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_scraped', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_asin'), ['asin'], unique=True)

    op.create_table('scrape_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Integer(), nullable=True),
    sa.Column('failed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bsr_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('bsr_rank', sa.Integer(), nullable=True),
    sa.Column('bsr_category', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bsr_history', schema=None) as batch_op:
        batch_op.create_index('idx_bsr_history_product_date', ['product_id', 'scraped_at'], unique=False)

    op.create_table('churn_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('asin', sa.String(length=10), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('units_ordered', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('conversion_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sessions', sa.Integer(), nullable=True),
    sa.Column('buy_box_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('bsr_current', sa.Integer(), nullable=True),
    sa.Column('bsr_trend', sa.String(length=20), nullable=True),
    sa.Column('listing_age_days', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['churn_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('churn_scores', schema=None) as batch_op:
        batch_op.create_index('idx_churn_scores_report_asin', ['report_id', 'asin'], unique=False)
        batch_op.create_index(batch_op.f('ix_churn_scores_asin'), ['asin'], unique=False)

    op.create_table('keyword_rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('is_sponsored', sa.Boolean(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keyword_rankings', schema=None) as batch_op:
        batch_op.create_index('idx_keyword_rankings_lookup', ['keyword_id', 'product_id', 'scraped_at'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('seller', sa.String(length=255), nullable=True),
    sa.Column('fulfillment', sa.String(length=20), nullable=True),
    sa.Column('is_deal', sa.Boolean(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index('idx_price_history_product_date', ['product_id', 'scraped_at'], unique=False)

    op.create_table('rating_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rating_history', schema=None) as batch_op:
        batch_op.create_index('idx_rating_history_product_date', ['product_id', 'scraped_at'], unique=False)

    op.create_table('seller_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('seller_name', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fulfillment', sa.String(length=20), nullable=True),
    sa.Column('is_buybox', sa.Boolean(), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seller_offers', schema=None) as batch_op:
        batch_op.create_index('idx_seller_offers_product', ['product_id', 'scraped_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller_offers', schema=None) as batch_op:
        batch_op.drop_index('idx_seller_offers_product')

    op.drop_table('seller_offers')
    with op.batch_alter_table('rating_history', schema=None) as batch_op:
        batch_op.drop_index('idx_rating_history_product_date')

    op.drop_table('rating_history')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index('idx_price_history_product_date')

    op.drop_table('price_history')
    with op.batch_alter_table('keyword_rankings', schema=None) as batch_op:
        batch_op.drop_index('idx_keyword_rankings_lookup')

    op.drop_table('keyword_rankings')
    with op.batch_alter_table('churn_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_churn_scores_asin'))
        batch_op.drop_index('idx_churn_scores_report_asin')

    op.drop_table('churn_scores')
    with op.batch_alter_table('bsr_history', schema=None) as batch_op:
        batch_op.drop_index('idx_bsr_history_product_date')

    op.drop_table('bsr_history')
    op.drop_table('scrape_jobs')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_asin'))

    op.drop_table('products')
    op.drop_table('keywords')
    op.drop_table('invoices')
    op.drop_table('churn_reports')
    # ### end Alembic commands ###
