-- GENERATED by node-app/scripts/gen_schema.py from the live SQLite schema.
-- Do not hand-edit: regenerate, so the DDL cannot drift from models.py.
--
-- 34 tables. churn_reports/churn_scores are deliberately ABSENT (0 rows,
-- referenced only by models.py — the router and template were already deleted), and
-- alembic_version is omitted because this stack owns its own migration history.

BEGIN;

CREATE TABLE IF NOT EXISTS ads_entity (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type VARCHAR(12) NOT NULL,
  entity_id VARCHAR(32) NOT NULL,
  parent_id VARCHAR(32),
  campaign_id VARCHAR(32),
  name VARCHAR(500),
  state VARCHAR(12),
  match_type VARCHAR(40),
  bid NUMERIC(12,2),
  default_bid NUMERIC(12,2),
  daily_budget NUMERIC(12,2),
  fetched_at TIMESTAMP,
  ad_product VARCHAR(4) NOT NULL DEFAULT 'sp'
);

CREATE INDEX IF NOT EXISTS idx_ads_entity_product ON ads_entity (ad_product, entity_type);
CREATE INDEX IF NOT EXISTS idx_ads_entity_campaign ON ads_entity (campaign_id);
CREATE INDEX IF NOT EXISTS idx_ads_entity_parent ON ads_entity (entity_type, parent_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_ads_entity_type_id ON ads_entity (entity_type, entity_id);

CREATE TABLE IF NOT EXISTS ads_mutation (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id VARCHAR(36) NOT NULL,
  entity_id VARCHAR(32) NOT NULL,
  entity_type VARCHAR(12) NOT NULL DEFAULT 'keyword',
  writer VARCHAR(12) NOT NULL DEFAULT 'keyword',
  text VARCHAR(500),
  campaign_id VARCHAR(32),
  ad_group_id VARCHAR(32),
  old_bid NUMERIC(12,2),
  new_bid NUMERIC(12,2),
  status VARCHAR(12) NOT NULL DEFAULT 'pending',
  error TEXT,
  rule_summary VARCHAR(300),
  reverts_run_id VARCHAR(36),
  created_at TIMESTAMP,
  sent_at TIMESTAMP,
  ad_product VARCHAR(4) NOT NULL DEFAULT 'sp',
  action VARCHAR(8) NOT NULL DEFAULT 'bid',
  old_state VARCHAR(12),
  new_state VARCHAR(12)
);

CREATE INDEX IF NOT EXISTS idx_ads_mutation_created ON ads_mutation (created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_ads_mutation_run_entity ON ads_mutation (run_id, entity_id);
CREATE INDEX IF NOT EXISTS idx_ads_mutation_entity ON ads_mutation (entity_id);
CREATE INDEX IF NOT EXISTS idx_ads_mutation_run ON ads_mutation (run_id);

CREATE TABLE IF NOT EXISTS ads_performance_daily (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day VARCHAR(10) NOT NULL,
  entity_id VARCHAR(32) NOT NULL,
  entity_type VARCHAR(12) NOT NULL DEFAULT 'target',
  campaign_id VARCHAR(32),
  ad_group_id VARCHAR(32),
  text VARCHAR(500),
  match_type VARCHAR(40),
  reported_bid NUMERIC(12,2),
  impressions INTEGER,
  clicks INTEGER,
  spend NUMERIC(12,2),
  orders INTEGER,
  sales NUMERIC(12,2),
  fetched_at TIMESTAMP,
  ad_product VARCHAR(4) NOT NULL DEFAULT 'sp'
);

CREATE INDEX IF NOT EXISTS idx_ads_daily_day_product ON ads_performance_daily (day, ad_product);
CREATE UNIQUE INDEX IF NOT EXISTS idx_ads_daily_day_entity ON ads_performance_daily (day, entity_id, ad_product);
CREATE INDEX IF NOT EXISTS idx_ads_daily_campaign ON ads_performance_daily (day, campaign_id);
CREATE INDEX IF NOT EXISTS idx_ads_daily_day ON ads_performance_daily (day);

CREATE TABLE IF NOT EXISTS ads_refresh (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  window_start VARCHAR(10),
  window_end VARCHAR(10),
  status VARCHAR(10) NOT NULL DEFAULT 'done',
  sp_rows INTEGER DEFAULT '0',
  sb_rows INTEGER DEFAULT '0',
  campaigns INTEGER DEFAULT '0',
  ad_groups INTEGER DEFAULT '0',
  error TEXT,
  sb_error TEXT,
  started_at TIMESTAMP,
  finished_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ads_refresh_started ON ads_refresh (started_at);

CREATE TABLE IF NOT EXISTS ads_rule (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  conditions_json JSONB,
  action VARCHAR(20),
  amount NUMERIC(12,2),
  window_days INTEGER DEFAULT '7',
  created_at TIMESTAMP,
  last_run_at TIMESTAMP,
  target_state VARCHAR(12)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_ads_rule_name ON ads_rule (name);

CREATE TABLE IF NOT EXISTS ads_snapshot (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  window_start VARCHAR(10) NOT NULL,
  window_end VARCHAR(10) NOT NULL,
  child_asin VARCHAR(10) NOT NULL,
  seller_sku VARCHAR(80) NOT NULL DEFAULT '',
  cost NUMERIC(12,2),
  attributed_sales NUMERIC(12,2),
  purchases INTEGER,
  clicks INTEGER,
  impressions INTEGER,
  fetched_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_ads_snapshot_window_asin_sku ON ads_snapshot (window_start, window_end, child_asin, seller_sku);

CREATE TABLE IF NOT EXISTS amazon_orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  amazon_order_id VARCHAR(20) NOT NULL,
  purchase_date_utc TIMESTAMP,
  latest_ship_date_utc TIMESTAMP,
  status VARCHAR(20),
  easyship_status VARCHAR(30),
  ship_service_level VARCHAR(60),
  order_total NUMERIC(12,2),
  currency VARCHAR(5),
  items_ordered INTEGER,
  items_shipped INTEGER,
  is_prime BOOLEAN,
  is_cod BOOLEAN,
  city VARCHAR(60),
  state VARCHAR(60),
  postal_code VARCHAR(12),
  first_seen_at TIMESTAMP,
  last_refreshed_at TIMESTAMP,
  items_fetched_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_amazon_orders_amazon_order_id ON amazon_orders (amazon_order_id);

CREATE TABLE IF NOT EXISTS economics_refresh (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  window_start VARCHAR(10),
  window_end VARCHAR(10),
  rows_stored INTEGER,
  error TEXT,
  started_at TIMESTAMP,
  finished_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS economics_snapshot (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  window_start VARCHAR(10) NOT NULL,
  window_end VARCHAR(10) NOT NULL,
  child_asin VARCHAR(10) NOT NULL,
  parent_asin VARCHAR(10),
  ordered_sales NUMERIC(12,2),
  refunded_sales NUMERIC(12,2),
  ad_spend NUMERIC(12,2),
  net_proceeds NUMERIC(12,2),
  units_ordered INTEGER,
  units_refunded INTEGER,
  net_units INTEGER,
  fees_json JSONB,
  ads_json JSONB,
  fetched_at TIMESTAMP,
  seller_sku VARCHAR(80)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_economics_snapshot_window_asin ON economics_snapshot (window_start, window_end, child_asin, seller_sku);

CREATE TABLE IF NOT EXISTS invoices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_no VARCHAR(30) NOT NULL,
  invoice_number INTEGER NOT NULL,
  shipment_id VARCHAR(50),
  date VARCHAR(20),
  supplier_gstin VARCHAR(20),
  recipient_gstin VARCHAR(20),
  recipient_state VARCHAR(50),
  fc_code VARCHAR(10),
  transporter VARCHAR(100),
  total_qty INTEGER,
  total_taxable NUMERIC(12,2),
  total_igst NUMERIC(12,2),
  total_amount NUMERIC(12,2),
  invoice_data JSONB,
  created_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS invoices_invoice_no_key ON invoices (invoice_no);

CREATE TABLE IF NOT EXISTS keywords (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  keyword TEXT NOT NULL,
  marketplace VARCHAR(10),
  is_active BOOLEAN,
  created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_packed_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pack_date VARCHAR(10) NOT NULL,
  asin VARCHAR(10) NOT NULL,
  units INTEGER,
  updated_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_order_packed_date_asin ON order_packed_entries (pack_date, asin);

CREATE TABLE IF NOT EXISTS order_packed_state (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pack_date VARCHAR(10) NOT NULL,
  amazon_order_id VARCHAR(20) NOT NULL,
  packed_at TIMESTAMP,
  packed_by VARCHAR(50),
  source VARCHAR(10)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_order_packed_state_date_order ON order_packed_state (pack_date, amazon_order_id);

CREATE TABLE IF NOT EXISTS portfolio_settings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(40) NOT NULL,
  value_json JSONB,
  updated_at TIMESTAMP,
  updated_by VARCHAR(50)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_portfolio_settings_name ON portfolio_settings (name);

CREATE TABLE IF NOT EXISTS product_categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_key VARCHAR(120) NOT NULL,
  product_label TEXT,
  priority INTEGER NOT NULL DEFAULT '6',
  source VARCHAR(10),
  updated_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_product_categories_key ON product_categories (product_key);

CREATE TABLE IF NOT EXISTS product_decision (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_asin VARCHAR(10) NOT NULL,
  decision VARCHAR(10) NOT NULL,
  note TEXT,
  snapshot_json JSONB,
  decided_at TIMESTAMP,
  decided_by VARCHAR(50)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_product_decision_parent ON product_decision (parent_asin);

CREATE TABLE IF NOT EXISTS product_prices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asin VARCHAR(20) NOT NULL,
  item TEXT,
  fba_sku VARCHAR(80),
  weight NUMERIC(10,3),
  brand VARCHAR(10),
  purchase_rate NUMERIC(12,2),
  hsn_code VARCHAR(10),
  gst_rate NUMERIC(5,2),
  updated_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_product_prices_asin ON product_prices (asin);

CREATE TABLE IF NOT EXISTS product_raw_stock (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product VARCHAR(120) NOT NULL,
  raw_kg NUMERIC(10,2),
  updated_at TIMESTAMP,
  updated_by VARCHAR(50)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_product_raw_stock_product ON product_raw_stock (product);

CREATE TABLE IF NOT EXISTS products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asin VARCHAR(10) NOT NULL,
  title TEXT,
  category TEXT,
  use_by VARCHAR(50),
  first_seen TIMESTAMP,
  last_scraped TIMESTAMP,
  is_active BOOLEAN
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_products_asin ON products (asin);

CREATE TABLE IF NOT EXISTS projection_refresh (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  window_start VARCHAR(10),
  window_end VARCHAR(10),
  rows_stored INTEGER DEFAULT '0',
  error TEXT,
  started_at TIMESTAMP,
  finished_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS projection_row (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_product VARCHAR(120) NOT NULL,
  brand VARCHAR(60),
  purchase_rate NUMERIC(10,2) DEFAULT '0',
  supplier_to_wh INTEGER DEFAULT '5',
  packing INTEGER DEFAULT '2',
  wh_to_ixd INTEGER DEFAULT '10',
  ixd_to_fba INTEGER DEFAULT '5',
  wh_buffer_days NUMERIC(6,1) DEFAULT '10',
  seasonal_impact NUMERIC(6,2) DEFAULT '1.0',
  needs_review BOOLEAN NOT NULL DEFAULT false,
  sales_source VARCHAR(10) NOT NULL DEFAULT 'sheet',
  last_month_sale NUMERIC(10,2) DEFAULT '0',
  seven_day_rate NUMERIC(10,2),
  thirty_day_rate NUMERIC(10,2),
  daily_rate NUMERIC(10,2) DEFAULT '0',
  diverged BOOLEAN NOT NULL DEFAULT false,
  current_fba_stock NUMERIC(10,1) DEFAULT '0',
  current_wh_stock NUMERIC(10,1) DEFAULT '0',
  updated_at TIMESTAMP,
  updated_by VARCHAR(60),
  excluded_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_projection_row_parent ON projection_row (parent_product);

CREATE TABLE IF NOT EXISTS scrape_jobs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_type VARCHAR(20),
  total_items INTEGER,
  completed INTEGER,
  failed INTEGER,
  status VARCHAR(20),
  started_at TIMESTAMP,
  finished_at TIMESTAMP,
  error_log TEXT
);

CREATE TABLE IF NOT EXISTS shipment_plans (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label VARCHAR(100),
  multiplier NUMERIC(4,1),
  status VARCHAR(20),
  min_cartons INTEGER,
  min_units INTEGER,
  created_at TIMESTAMP,
  closed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(32) NOT NULL,
  full_name VARCHAR(120),
  password_hash VARCHAR(255) NOT NULL,
  permissions VARCHAR(255),
  is_admin BOOLEAN NOT NULL,
  is_active BOOLEAN NOT NULL,
  created_by VARCHAR(32),
  created_at TIMESTAMP,
  last_login_at TIMESTAMP,
  must_change_password BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_users_username ON users (username);

CREATE TABLE IF NOT EXISTS amazon_order_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL,
  asin VARCHAR(10) NOT NULL,
  seller_sku VARCHAR(80),
  title TEXT,
  quantity_ordered INTEGER,
  quantity_shipped INTEGER,
  item_price NUMERIC(12,2),
  item_tax NUMERIC(12,2),
  promotion_discount NUMERIC(12,2),
  FOREIGN KEY (order_id) REFERENCES amazon_orders(id)
);

CREATE INDEX IF NOT EXISTS idx_amazon_order_items_order_asin ON amazon_order_items (order_id, asin);

CREATE TABLE IF NOT EXISTS bsr_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL,
  bsr_rank INTEGER,
  bsr_category TEXT,
  scraped_at TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE INDEX IF NOT EXISTS idx_bsr_history_product_date ON bsr_history (product_id, scraped_at);

CREATE TABLE IF NOT EXISTS keyword_rankings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  keyword_id INTEGER NOT NULL,
  product_id INTEGER NOT NULL,
  rank_position INTEGER,
  page_number INTEGER,
  is_sponsored BOOLEAN,
  scraped_at TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id),
  FOREIGN KEY (keyword_id) REFERENCES keywords(id)
);

CREATE INDEX IF NOT EXISTS idx_keyword_rankings_lookup ON keyword_rankings (keyword_id, product_id, scraped_at);

CREATE TABLE IF NOT EXISTS price_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL,
  price NUMERIC(10,2),
  seller VARCHAR(255),
  fulfillment VARCHAR(20),
  is_deal BOOLEAN,
  scraped_at TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE INDEX IF NOT EXISTS idx_price_history_product_date ON price_history (product_id, scraped_at);

CREATE TABLE IF NOT EXISTS rating_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL,
  rating NUMERIC(2,1),
  rating_count INTEGER,
  scraped_at TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE INDEX IF NOT EXISTS idx_rating_history_product_date ON rating_history (product_id, scraped_at);

CREATE TABLE IF NOT EXISTS seller_offers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL,
  seller_name VARCHAR(255),
  price NUMERIC(10,2),
  fulfillment VARCHAR(20),
  is_buybox BOOLEAN,
  condition VARCHAR(50),
  scraped_at TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE INDEX IF NOT EXISTS idx_seller_offers_product ON seller_offers (product_id, scraped_at);

CREATE TABLE IF NOT EXISTS shipment_packing_days (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id INTEGER NOT NULL,
  pack_date VARCHAR(10) NOT NULL,
  status VARCHAR(12),
  hold_reason TEXT,
  total_units INTEGER,
  total_cartons INTEGER,
  submitted_by VARCHAR(20),
  submitted_at TIMESTAMP,
  verified_at TIMESTAMP,
  invoice_id INTEGER,
  inbound_plan_id VARCHAR(60),
  amazon_shipment_id VARCHAR(60),
  shipment_confirmation_id VARCHAR(30),
  destination_warehouse_id VARCHAR(10),
  destination_state VARCHAR(50),
  carried_from_plan_id INTEGER,
  FOREIGN KEY (plan_id) REFERENCES shipment_plans(id),
  FOREIGN KEY (invoice_id) REFERENCES invoices(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_packing_days_plan_date ON shipment_packing_days (plan_id, pack_date);

CREATE TABLE IF NOT EXISTS shipment_plan_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id INTEGER NOT NULL,
  asin VARCHAR(10) NOT NULL,
  fba_sku VARCHAR(100),
  brand VARCHAR(4),
  item TEXT,
  sort_product VARCHAR(120),
  weight NUMERIC(6,3),
  sales_7d INTEGER,
  projection INTEGER,
  fba_stock INTEGER,
  deficit INTEGER,
  shipment_plan INTEGER,
  available INTEGER,
  s BOOLEAN,
  m BOOLEAN,
  b BOOLEAN,
  brand_rank INTEGER NOT NULL,
  excluded_at TIMESTAMP,
  FOREIGN KEY (plan_id) REFERENCES shipment_plans(id)
);

CREATE INDEX IF NOT EXISTS idx_shipment_plan_items_plan_asin ON shipment_plan_items (plan_id, asin);

CREATE TABLE IF NOT EXISTS user_login_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(32) NOT NULL,
  user_id INTEGER,
  success BOOLEAN NOT NULL,
  via VARCHAR(16) NOT NULL,
  ip_address VARCHAR(64),
  created_at TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_user_login_events_user ON user_login_events (user_id);
CREATE INDEX IF NOT EXISTS idx_user_login_events_created ON user_login_events (created_at);

CREATE TABLE IF NOT EXISTS shipment_packing_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day_id INTEGER NOT NULL,
  asin VARCHAR(10) NOT NULL,
  units INTEGER,
  note TEXT,
  updated_at TIMESTAMP,
  FOREIGN KEY (day_id) REFERENCES shipment_packing_days(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_packing_entries_day_asin ON shipment_packing_entries (day_id, asin);

COMMIT;