"""Generate the Postgres DDL for THIS app's schema, from the live SQLite database.

Run from the repo root:  venv/Scripts/python scripts/postgres/gen_schema.py

**For the SQLite -> PostgreSQL migration** described in the plan appendix. Written during an
abandoned Node rewrite and kept because it is the risky half of that migration, already built and
proven: the rewrite was dropped, the schema work was not.

**Generated, not typed by hand, and that is the point.** 344 columns across 34 tables is exactly
the volume at which a transcription slip becomes invisible — and a wrong `NUMERIC` precision is
invisible until money is computed. The source of truth is `PRAGMA table_info`, i.e. what
`models.py` actually produced, so the DDL cannot drift from the app that has been running.

Type mapping, and the three that are decisions rather than translations:

* `INTEGER` primary key -> `GENERATED BY DEFAULT AS IDENTITY`, never `SERIAL`. The classic silent
  failure of a copy is inserting explicit ids from the old database and leaving the sequence at 1,
  so the next insert collides on the primary key. `BY DEFAULT` lets the seed supply explicit ids
  AND `setval` afterwards, which `seed_from_sqlite.py` does.
* `DATETIME` -> `TIMESTAMP` (no timezone). The app stores naive UTC via `datetime.utcnow()`, and
  `TIMESTAMPTZ` would make Postgres convert on read using the SESSION timezone — silently shifting
  every stored timestamp by whatever the client is set to. Keeping it naive preserves the existing
  contract exactly, and `app/ist.py` remains the only thing that decides which day it is.
* The six JSON-carrying `TEXT` columns -> `JSONB`. They hold real JSON (`fees_json`, `ads_json`,
  `snapshot_json`, `value_json`, `conditions_json`, `invoice_data`) and Postgres can index and
  query them. The one genuine upgrade in the mapping, and the seed must therefore PARSE rather
  than copy those strings.

`churn_reports` and `churn_scores` are deliberately absent: 0 rows, referenced only by
`models.py`, and their router and template were already deleted. `alembic_version` is omitted
because Alembic stamps it itself.
"""
from __future__ import annotations

import json
import pathlib
import re
import sqlite3
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent.parent
HERE = pathlib.Path(__file__).resolve().parent
DUMP = HERE / "schema_dump.json"
SQLITE = REPO / "tracker.db"

#: Tables with no code behind them. Named here rather than filtered silently, so the next reader
#: can see the decision and reverse it.
DEAD_TABLES = {"churn_reports", "churn_scores", "alembic_version"}


def dump_sqlite_schema() -> dict:
    """Reflect the live schema. **Read-only** (`mode=ro`), so this cannot touch the running app."""
    if not SQLITE.exists():
        raise SystemExit(f"{SQLITE} not found")
    con = sqlite3.connect(f"file:{SQLITE.as_posix()}?mode=ro", uri=True)
    tables = [
        row[0]
        for row in con.execute(
            "SELECT name FROM sqlite_master WHERE type='table' "
            "AND name NOT LIKE 'sqlite_%' ORDER BY name"
        )
    ]
    out: dict = {}
    for table in tables:
        if table in DEAD_TABLES:
            continue
        out[table] = {
            "columns": [
                dict(cid=r[0], name=r[1], type=r[2], notnull=r[3], default=r[4], pk=r[5])
                for r in con.execute(f'PRAGMA table_info("{table}")')
            ],
            "indexes": [
                dict(
                    name=r[1],
                    unique=bool(r[2]),
                    origin=r[3],
                    cols=[x[2] for x in con.execute(f'PRAGMA index_info("{r[1]}")')],
                )
                for r in con.execute(f'PRAGMA index_list("{table}")')
            ],
            "fks": [
                dict(col=r[3], ref_table=r[2], ref_col=r[4])
                for r in con.execute(f'PRAGMA foreign_key_list("{table}")')
            ],
        }
    con.close()
    DUMP.write_text(json.dumps(out, indent=1), encoding="utf-8")
    return out

#: Columns whose TEXT holds JSON. Named explicitly rather than guessed from the suffix: a
#: `_json` suffix is a naming convention, and `invoice_data` breaks it while genuinely holding
#: "Full JSON of the invoice". Getting this wrong either way is silent — a JSON string in a TEXT
#: column still reads fine, it just cannot be queried.
#: **Verified against the dump at generation time** — see `_check_json_columns`. The first
#: version of this set said `("ads_snapshot", "snapshot_json")`; the column actually belongs to
#: `product_decision`, so it silently stayed TEXT and nothing failed. With 344 columns that slip
#: is invisible, which is exactly why the set is now asserted rather than trusted.
JSON_COLUMNS = {
    ("economics_snapshot", "fees_json"),
    ("economics_snapshot", "ads_json"),
    ("product_decision", "snapshot_json"),
    ("portfolio_settings", "value_json"),
    ("ads_rule", "conditions_json"),
    ("invoices", "invoice_data"),
}


def _check_json_columns(schema: dict) -> None:
    """Every declared JSON column must EXIST, and every `*_json` column must be declared.

    Both directions, because each catches a different mistake: a typo'd table name leaves the
    column as TEXT (silent), and a new `*_json` column added later would quietly miss the JSONB
    mapping (also silent). The same two-way discipline `test_unauthenticated_access.py` uses for
    its exemption list.
    """
    present = {
        (table, col["name"])
        for table, spec in schema.items()
        for col in spec["columns"]
    }
    missing = JSON_COLUMNS - present
    if missing:
        raise SystemExit(
            f"JSON_COLUMNS names columns that do not exist: {sorted(missing)}. "
            "They would silently remain TEXT."
        )
    suffixed = {(t, c) for (t, c) in present if c.endswith("_json")}
    undeclared = suffixed - JSON_COLUMNS
    if undeclared:
        raise SystemExit(
            f"these *_json columns are not declared as JSONB: {sorted(undeclared)}. "
            "Add them to JSON_COLUMNS, or state why they hold something other than JSON."
        )

#: Boolean defaults in SQLite are stored as the integers 0/1.
BOOL_DEFAULT = {"0": "false", "1": "true"}


def pg_type(table: str, col: dict) -> str:
    raw = (col["type"] or "").upper()
    name = col["name"]

    if (table, name) in JSON_COLUMNS:
        return "JSONB"
    if raw == "INTEGER":
        return "INTEGER"
    if raw == "TEXT":
        return "TEXT"
    if raw == "BOOLEAN":
        return "BOOLEAN"
    if raw == "DATETIME":
        return "TIMESTAMP"
    if raw.startswith("VARCHAR"):
        return raw.replace("VARCHAR", "VARCHAR")
    if raw.startswith("NUMERIC"):
        # Precision is preserved verbatim. NUMERIC(12,2) is money; NUMERIC(2,1) is a star
        # rating. Widening "to be safe" would let a rating of 99 be stored, which is exactly
        # the bug `good_rating: 99` taught this codebase to range-check for.
        return raw.replace(" ", "")
    raise SystemExit(f"unmapped type {raw!r} on {table}.{name}")


def default_clause(table: str, col: dict) -> str:
    raw = col["default"]
    if raw is None:
        return ""
    text = str(raw).strip()
    pg = pg_type(table, col)
    if pg == "BOOLEAN":
        return f" DEFAULT {BOOL_DEFAULT.get(text, text)}"
    # SQLAlchemy's `default=datetime.utcnow` is applied in PYTHON, so SQLite records no server
    # default for it and there is nothing to translate. Anything else is a literal.
    if text.upper() in {"CURRENT_TIMESTAMP", "NULL"}:
        return ""
    return f" DEFAULT {text}"


def dependency_order(schema: dict) -> list[str]:
    """Tables sorted so every referenced table is created BEFORE the one referencing it.

    **Alphabetical order does not work and Postgres says so**: `amazon_order_items` sorts before
    `amazon_orders` and its foreign key fails with *relation "amazon_orders" does not exist*.
    SQLite tolerates a forward reference here (it resolves FKs lazily and has them off by
    default), which is precisely why the original schema never had to care about this.

    A topological sort, with ties broken alphabetically so the output is stable — a generator
    whose diff churns between runs is one nobody reads.

    Self-references are ignored as a dependency (a table can reference its own column, as
    `shipment_plans.carried_from_plan_id` does) since it exists by the time the FK is declared.
    """
    deps = {
        table: {
            fk["ref_table"]
            for fk in spec["fks"]
            if fk["ref_table"] != table and fk["ref_table"] in schema
        }
        for table, spec in schema.items()
    }
    ordered: list[str] = []
    placed: set[str] = set()
    while len(ordered) < len(schema):
        ready = sorted(t for t in schema if t not in placed and deps[t] <= placed)
        if not ready:
            # A cycle. Reported rather than silently broken, because the fix is a deferred
            # constraint and that is a decision, not something to guess at.
            remaining = sorted(set(schema) - placed)
            raise SystemExit(
                f"circular foreign keys among {remaining} — needs a deferred constraint"
            )
        ordered.extend(ready)
        placed.update(ready)
    return ordered


def build() -> str:
    # Reflected fresh every run rather than read from a stale dump: the whole guarantee is that the
    # DDL matches the database the app is actually running on.
    schema = dump_sqlite_schema()
    _check_json_columns(schema)

    lines: list[str] = [
        "-- GENERATED by scripts/postgres/gen_schema.py from the live SQLite schema.",
        "-- Do not hand-edit: regenerate, so the DDL cannot drift from models.py.",
        "--",
        f"-- {len(schema)} tables. churn_reports/churn_scores are deliberately ABSENT (0 rows,",
        "-- referenced only by models.py — the router and template were already deleted), and",
        "-- alembic_version is omitted because this stack owns its own migration history.",
        "",
        "BEGIN;",
        "",
    ]

    for table in dependency_order(schema):
        spec = schema[table]
        lines.append(f"CREATE TABLE IF NOT EXISTS {table} (")
        parts: list[str] = []
        pk = [c for c in spec["columns"] if c["pk"]]
        for col in spec["columns"]:
            pg = pg_type(table, col)
            if col["pk"] and pg == "INTEGER" and len(pk) == 1:
                # Identity rather than SERIAL — see the module docstring.
                parts.append(
                    f"  {col['name']} INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
                )
                continue
            piece = f"  {col['name']} {pg}"
            if col["notnull"]:
                piece += " NOT NULL"
            piece += default_clause(table, col)
            parts.append(piece)

        if len(pk) > 1:
            parts.append(f"  PRIMARY KEY ({', '.join(c['name'] for c in pk)})")

        for fk in spec["fks"]:
            # ON DELETE is deliberately NOT declared. SQLAlchemy's `cascade="all, delete-orphan"`
            # is enforced in the ORM, not the database, and this app's history includes a cascade
            # deleting 400 units of real packed stock. Reproducing that at the DDL level would
            # make the same accident unrecoverable and invisible.
            parts.append(
                f"  FOREIGN KEY ({fk['col']}) REFERENCES {fk['ref_table']}({fk['ref_col']})"
            )

        lines.append(",\n".join(parts))
        lines.append(");")
        lines.append("")

        for idx in spec["indexes"]:
            # `origin == "pk"` is the implicit primary-key index; "u" is a UNIQUE constraint that
            # SQLite auto-named. Both already exist by virtue of the table definition, but a
            # UNIQUE declared via Column(unique=True) shows up here as an auto index and DOES
            # need recreating — those carry the app's real invariants, like
            # (day_id, asin) stopping a flaky warehouse phone double-counting a save.
            if idx["origin"] == "pk":
                continue
            unique = "UNIQUE " if idx["unique"] else ""
            name = idx["name"]
            if name.startswith("sqlite_autoindex"):
                name = f"{table}_{'_'.join(idx['cols'])}_key"
            cols = ", ".join(idx["cols"])
            lines.append(
                f"CREATE {unique}INDEX IF NOT EXISTS {name} ON {table} ({cols});"
            )
        if spec["indexes"]:
            lines.append("")

    lines.append("COMMIT;")
    return "\n".join(lines)


if __name__ == "__main__":
    ddl = build()
    out = HERE / "schema.sql"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(ddl, encoding="utf-8")
    tables = len(re.findall(r"^CREATE TABLE", ddl, re.M))
    indexes = len(re.findall(r"^CREATE (?:UNIQUE )?INDEX", ddl, re.M))
    print(f"wrote {out.relative_to(REPO)}")
    print(f"  {tables} tables, {indexes} indexes, {len(ddl.splitlines())} lines")
